version: "3"
services:
  board_database:
    container_name: board_database
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: jpa_rest_board_example
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  board:
    container_name: board
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 20000:20000
    depends_on:
      - board_database