
server:
  port: 18080
spring:
  profiles: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_rest_board_example?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: jpa_rest_board_example_admin
    password: jpa_rest_board_example_pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    devcrema: debug
    org:
      hibernate: info
      springframework:
        security: info